import { Footer } from '@/components/footer'
import { Header } from '@/components/header'
import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.css'

const dmSans = DM_Sans({
    variable: '--font-DM-sans',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: {
        template: '%s | Lab Yes!',
        default: 'Lab Yes!',
    },
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="pt-BR">
            <body
                className={`${dmSans.variable} mx-auto flex min-h-screen max-w-[1440px] flex-col bg-ly-white antialiased`}
            >
                <Header />
                <main className="flex-grow px-8 py-3">{children}</main>
                <Footer />
            </body>
        </html>
    )
}
