import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import './globals.css'

const dmSans = DM_Sans({
    variable: '--font-DM-sans',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: {
        default: 'Lab Yes!',
        template: '%s | Lab Yes!',
    },
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="pt-BR">
            <body className={`${dmSans.variable} antialiased`}>{children}</body>
        </html>
    )
}
